// Top 100 U.S. Equities + ETFs + Macro assets for MarketMind
export interface TickerInfo {
  symbol: string;
  name: string;
  sector?: string;
  type: "equity" | "etf" | "index" | "commodity";
}

export const TICKER_UNIVERSE: TickerInfo[] = [
  // Indices & Broad ETFs
  { symbol: "SPY", name: "S&P 500 ETF", type: "etf" },
  { symbol: "QQQ", name: "Nasdaq 100 ETF", type: "etf" },
  { symbol: "^VIX", name: "VIX Volatility Index", type: "index" },

  // Sector ETFs
  { symbol: "XLK", name: "Technology Select Sector", sector: "Technology", type: "etf" },
  { symbol: "XLE", name: "Energy Select Sector", sector: "Energy", type: "etf" },
  { symbol: "XLF", name: "Financial Select Sector", sector: "Financials", type: "etf" },
  { symbol: "XLI", name: "Industrial Select Sector", sector: "Industrials", type: "etf" },
  { symbol: "XLY", name: "Consumer Discretionary Select", sector: "Consumer Discretionary", type: "etf" },
  { symbol: "XLP", name: "Consumer Staples Select", sector: "Consumer Staples", type: "etf" },
  { symbol: "XLV", name: "Health Care Select Sector", sector: "Healthcare", type: "etf" },
  { symbol: "XLB", name: "Materials Select Sector", sector: "Materials", type: "etf" },

  // Macro Assets
  { symbol: "GLD", name: "SPDR Gold Shares", type: "commodity" },
  { symbol: "USO", name: "United States Oil Fund", type: "commodity" },
  { symbol: "TLT", name: "iShares 20+ Year Treasury", type: "etf" },

  // Top 100 U.S. Equities by Market Cap
  { symbol: "AAPL", name: "Apple Inc.", sector: "Technology", type: "equity" },
  { symbol: "MSFT", name: "Microsoft Corporation", sector: "Technology", type: "equity" },
  { symbol: "GOOGL", name: "Alphabet Inc.", sector: "Technology", type: "equity" },
  { symbol: "AMZN", name: "Amazon.com Inc.", sector: "Consumer Discretionary", type: "equity" },
  { symbol: "NVDA", name: "NVIDIA Corporation", sector: "Technology", type: "equity" },
  { symbol: "META", name: "Meta Platforms Inc.", sector: "Technology", type: "equity" },
  { symbol: "TSLA", name: "Tesla Inc.", sector: "Consumer Discretionary", type: "equity" },
  { symbol: "BRK-B", name: "Berkshire Hathaway", sector: "Financials", type: "equity" },
  { symbol: "LLY", name: "Eli Lilly and Company", sector: "Healthcare", type: "equity" },
  { symbol: "AVGO", name: "Broadcom Inc.", sector: "Technology", type: "equity" },
  { symbol: "JPM", name: "JPMorgan Chase & Co.", sector: "Financials", type: "equity" },
  { symbol: "V", name: "Visa Inc.", sector: "Financials", type: "equity" },
  { symbol: "UNH", name: "UnitedHealth Group", sector: "Healthcare", type: "equity" },
  { symbol: "XOM", name: "Exxon Mobil Corporation", sector: "Energy", type: "equity" },
  { symbol: "MA", name: "Mastercard Inc.", sector: "Financials", type: "equity" },
  { symbol: "COST", name: "Costco Wholesale", sector: "Consumer Staples", type: "equity" },
  { symbol: "HD", name: "The Home Depot", sector: "Consumer Discretionary", type: "equity" },
  { symbol: "PG", name: "Procter & Gamble", sector: "Consumer Staples", type: "equity" },
  { symbol: "JNJ", name: "Johnson & Johnson", sector: "Healthcare", type: "equity" },
  { symbol: "WMT", name: "Walmart Inc.", sector: "Consumer Staples", type: "equity" },
  { symbol: "NFLX", name: "Netflix Inc.", sector: "Technology", type: "equity" },
  { symbol: "CRM", name: "Salesforce Inc.", sector: "Technology", type: "equity" },
  { symbol: "BAC", name: "Bank of America", sector: "Financials", type: "equity" },
  { symbol: "ORCL", name: "Oracle Corporation", sector: "Technology", type: "equity" },
  { symbol: "ABBV", name: "AbbVie Inc.", sector: "Healthcare", type: "equity" },
  { symbol: "CVX", name: "Chevron Corporation", sector: "Energy", type: "equity" },
  { symbol: "MRK", name: "Merck & Co.", sector: "Healthcare", type: "equity" },
  { symbol: "KO", name: "The Coca-Cola Company", sector: "Consumer Staples", type: "equity" },
  { symbol: "AMD", name: "Advanced Micro Devices", sector: "Technology", type: "equity" },
  { symbol: "PEP", name: "PepsiCo Inc.", sector: "Consumer Staples", type: "equity" },
  { symbol: "TMO", name: "Thermo Fisher Scientific", sector: "Healthcare", type: "equity" },
  { symbol: "ADBE", name: "Adobe Inc.", sector: "Technology", type: "equity" },
  { symbol: "LIN", name: "Linde plc", sector: "Materials", type: "equity" },
  { symbol: "CSCO", name: "Cisco Systems", sector: "Technology", type: "equity" },
  { symbol: "ACN", name: "Accenture plc", sector: "Technology", type: "equity" },
  { symbol: "WFC", name: "Wells Fargo & Co.", sector: "Financials", type: "equity" },
  { symbol: "MCD", name: "McDonald's Corporation", sector: "Consumer Discretionary", type: "equity" },
  { symbol: "ABT", name: "Abbott Laboratories", sector: "Healthcare", type: "equity" },
  { symbol: "DHR", name: "Danaher Corporation", sector: "Healthcare", type: "equity" },
  { symbol: "TXN", name: "Texas Instruments", sector: "Technology", type: "equity" },
  { symbol: "PM", name: "Philip Morris International", sector: "Consumer Staples", type: "equity" },
  { symbol: "INTU", name: "Intuit Inc.", sector: "Technology", type: "equity" },
  { symbol: "IBM", name: "International Business Machines", sector: "Technology", type: "equity" },
  { symbol: "DIS", name: "The Walt Disney Company", sector: "Communication", type: "equity" },
  { symbol: "QCOM", name: "QUALCOMM Inc.", sector: "Technology", type: "equity" },
  { symbol: "VZ", name: "Verizon Communications", sector: "Communication", type: "equity" },
  { symbol: "CAT", name: "Caterpillar Inc.", sector: "Industrials", type: "equity" },
  { symbol: "NOW", name: "ServiceNow Inc.", sector: "Technology", type: "equity" },
  { symbol: "GE", name: "GE Aerospace", sector: "Industrials", type: "equity" },
  { symbol: "AMGN", name: "Amgen Inc.", sector: "Healthcare", type: "equity" },
  { symbol: "ISRG", name: "Intuitive Surgical", sector: "Healthcare", type: "equity" },
  { symbol: "SPGI", name: "S&P Global Inc.", sector: "Financials", type: "equity" },
  { symbol: "PFE", name: "Pfizer Inc.", sector: "Healthcare", type: "equity" },
  { symbol: "AXP", name: "American Express", sector: "Financials", type: "equity" },
  { symbol: "BKNG", name: "Booking Holdings", sector: "Consumer Discretionary", type: "equity" },
  { symbol: "GS", name: "Goldman Sachs Group", sector: "Financials", type: "equity" },
  { symbol: "BLK", name: "BlackRock Inc.", sector: "Financials", type: "equity" },
  { symbol: "UBER", name: "Uber Technologies", sector: "Technology", type: "equity" },
  { symbol: "T", name: "AT&T Inc.", sector: "Communication", type: "equity" },
  { symbol: "RTX", name: "RTX Corporation", sector: "Industrials", type: "equity" },
  { symbol: "LOW", name: "Lowe's Companies", sector: "Consumer Discretionary", type: "equity" },
  { symbol: "AMAT", name: "Applied Materials", sector: "Technology", type: "equity" },
  { symbol: "NEE", name: "NextEra Energy", sector: "Utilities", type: "equity" },
  { symbol: "SYK", name: "Stryker Corporation", sector: "Healthcare", type: "equity" },
  { symbol: "MDLZ", name: "Mondelez International", sector: "Consumer Staples", type: "equity" },
  { symbol: "ELV", name: "Elevance Health", sector: "Healthcare", type: "equity" },
  { symbol: "LRCX", name: "Lam Research", sector: "Technology", type: "equity" },
  { symbol: "PLD", name: "Prologis Inc.", sector: "Real Estate", type: "equity" },
  { symbol: "VRTX", name: "Vertex Pharmaceuticals", sector: "Healthcare", type: "equity" },
  { symbol: "PANW", name: "Palo Alto Networks", sector: "Technology", type: "equity" },
  { symbol: "REGN", name: "Regeneron Pharmaceuticals", sector: "Healthcare", type: "equity" },
  { symbol: "KLAC", name: "KLA Corporation", sector: "Technology", type: "equity" },
  { symbol: "SNPS", name: "Synopsys Inc.", sector: "Technology", type: "equity" },
  { symbol: "CDNS", name: "Cadence Design Systems", sector: "Technology", type: "equity" },
  { symbol: "BSX", name: "Boston Scientific", sector: "Healthcare", type: "equity" },
  { symbol: "SCHW", name: "Charles Schwab", sector: "Financials", type: "equity" },
  { symbol: "FI", name: "Fiserv Inc.", sector: "Financials", type: "equity" },
  { symbol: "CME", name: "CME Group Inc.", sector: "Financials", type: "equity" },
  { symbol: "SO", name: "Southern Company", sector: "Utilities", type: "equity" },
  { symbol: "BMY", name: "Bristol-Myers Squibb", sector: "Healthcare", type: "equity" },
  { symbol: "CRWD", name: "CrowdStrike Holdings", sector: "Technology", type: "equity" },
  { symbol: "COP", name: "ConocoPhillips", sector: "Energy", type: "equity" },
  { symbol: "DE", name: "Deere & Company", sector: "Industrials", type: "equity" },
  { symbol: "ABNB", name: "Airbnb Inc.", sector: "Consumer Discretionary", type: "equity" },
  { symbol: "PLTR", name: "Palantir Technologies", sector: "Technology", type: "equity" },
  { symbol: "COIN", name: "Coinbase Global", sector: "Financials", type: "equity" },
  { symbol: "ARM", name: "Arm Holdings", sector: "Technology", type: "equity" },
];

// Quick lookup map
export const TICKER_MAP = new Map(TICKER_UNIVERSE.map(t => [t.symbol, t]));

// Get all unique sectors
export const ALL_SECTORS = Array.from(new Set(TICKER_UNIVERSE.filter(t => t.sector).map(t => t.sector!))).sort();
